service: collections

configValidationMode: error

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!package*'
    - '!petpy/**'
    - '!README.md'

provider:
  name: aws
  region: us-east-1
  runtime: python3.11
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        - Effect: Allow
          Action:
            - 's3:*'
          Resource:
            Fn::Join:
              - ''
              - - "arn:aws:s3:::"
                - "Ref" : "CollectionsBucket"
                - '/*'

plugins:
  - serverless-dotenv-plugin

resources:
  Resources:
    CollectionsBucket:
      Type: AWS::S3::Bucket
  Outputs:
    CollectionsBucket:
      Description: Name of the Collections Bucket
      Value: !Ref CollectionsBucket
    CollectionsBucketUnderscore:
      Description: Name of the Collections Bucket replaced with underscores - used by Glue Crawler
      Value: 
        Fn::Join:
          - '_'
          - Fn::Split:
            - '-'
            - !Ref CollectionsBucket

functions:
  myFunction:
    handler: handler.handler
    layers:
      - arn:aws:lambda:${self:provider.region}:336392948345:layer:AWSSDKPandas-Python311:8
      - !Ref PetpyLambdaLayer
    environment:
      S3_BUCKET_NAME: !Ref CollectionsBucket
    package:
      patterns:
        - 'handler.py'

layers:
  petpy:
    path: petpy
    name: ${sls:stage}-petpy
    description: Petpy module
    compatibleRuntimes:
      - python3.11
    compatibleArchitectures:
      - x86_64
    retain: false


