service: user

configValidationMode: error

package:
  individually: true
  exclude:
    - ./**

provider:
  name: aws
  region: us-east-1
  runtime: python3.11
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        - Effect: Allow
          Action:
            - 's3:*'
          Resource:
            Fn::Join:
              - ''
              - - "arn:aws:s3:::"
                - "Ref" : "UserBucket"
                - '/*'

plugins:
  - serverless-dotenv-plugin

resources:
  Resources:
    UserBucket:
      Type: AWS::S3::Bucket

functions:
  myFunction:
    handler: handler.handler
    environment:
      S3_BUCKET_NAME: !Ref UserBucket
    package:
      include:
        - 'handler.py'


